# Generated by Django 3.2 on 2021-07-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210714_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_answered_question',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
