# Generated by Django 3.2 on 2021-07-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='github_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_id',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
