# Generated by Django 3.2 on 2021-06-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_person_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='linkedin_id',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
