# Generated by Django 3.2 on 2021-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_choice_course_question'),
        ('user', '0002_auto_20210522_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='resume',
        ),
        migrations.AddField(
            model_name='person',
            name='courses',
            field=models.ManyToManyField(related_name='persons', to='course.Course'),
        ),
        migrations.AddField(
            model_name='person',
            name='github_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
