# Generated by Django 3.2 on 2021-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210707_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='job',
            name='work_time',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('R', 'Remote')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
