# Generated by Django 3.2 on 2021-07-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210707_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Tehran', max_length=20),
            preserve_default=False,
        ),
    ]
