# Generated by Django 3.2 on 2021-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='field',
            field=models.CharField(choices=[('B', 'Backend'), ('F', 'Frontend')], default='B', max_length=1),
            preserve_default=False,
        ),
    ]
