# Generated by Django 3.2 on 2021-07-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='field',
            field=models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end')], max_length=1),
        ),
    ]
